### ISSUE TITLE
Multi-agent MDPs

### ISSUE THREAD

**Issue by alecive** [Svalorzen/AI-Toolbox#18]
Hey @Svalorzen ,

what is your plan w.r.t. multi-agent MDPs? do you plan on adding them at some point?

**Comment by Svalorzen** [comment]
At the moment I am focusing most efforts into finishing all Python wrappers and a couple of other things, then I could say that the project has reached some sort of 1.0 version. This shouldn't take more than a month (upper bound) I hope. Probably a couple of weeks.

Multi-agent MDPs are definitely possible. I have tried to implement multi-agent Q-Learning, but unfortunately I could not completely figure out the backpropagation algorithm there. Tried contacting the authors but got back zero info since the paper is so old.

If you have any particular interests/papers to implement/ideas feel free to add them. Issue #7 is the place!

**Comment by Svalorzen** [comment]
At the moment I am focusing most efforts into finishing all Python wrappers and a couple of other things, then I could say that the project has reached some sort of 1.0 version. This shouldn't take more than a month (upper bound) I hope. Probably a couple of weeks.

Multi-agent MDPs are definitely possible. I have tried to implement multi-agent Q-Learning, but unfortunately I could not completely figure out the backpropagation algorithm there. Tried contacting the authors but got back zero info since the paper is so old.

If you have any particular interests/papers to implement/ideas feel free to add them. Issue #7 is the place!

**Comment by Svalorzen** [comment]
At the moment I am focusing most efforts into finishing all Python wrappers and a couple of other things, then I could say that the project has reached some sort of 1.0 version. This shouldn't take more than a month (upper bound) I hope. Probably a couple of weeks.

Multi-agent MDPs are definitely possible. I have tried to implement multi-agent Q-Learning, but unfortunately I could not completely figure out the backpropagation algorithm there. Tried contacting the authors but got back zero info since the paper is so old.

If you have any particular interests/papers to implement/ideas feel free to add them. Issue #7 is the place!

**Comment by alecive** [comment]
Thank you for the information! I might try to work a bit on that at some point :)

**Comment by Svalorzen** [comment]
@alecive Sure =) In any case, if you have any ideas I'd really appreciate you pushing them out.

I maintain this library for many reasons, one of which is because I really enjoy implementing papers, and a good list of cool stuff (that people need) to try out is always nice to have. Looking out papers to implement is always one of the hardest things to do for me since I have little time to browse conference results, so any help in that direction is really appreciated. Ty!
