### ISSUE TITLE
How to save policy to file in Python

### ISSUE THREAD

**Issue by JFan2016** [Svalorzen/AI-Toolbox#23]
Hi Svalorzen,

When I try to save the policy using pickle, I received error: 
`RuntimeError: Pickling of "MDP.QGreedyPolicy" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)`
How do I save the policy?

Thank you!
Jing

**Comment by Svalorzen** [comment]
Unfortunately I didn't really add in support for pickles yet (since I never actually used them). I could look into it though - it seems to be a little time consuming though so I'm not sure how much time it'll take.

In the meantime, you can probably just somehow convert your QFunction to some format you can save. It has a `shape` function so you can just loop over it and save all the values it has.

Afterwards, you can create an `MDP.Matrix2D` instance of the same size, and copy the saved contents into it. This you can pass into a new instance of `MDP.QGreedyPolicy` and it should work the same as before.

**Comment by Svalorzen** [comment]
Actually, I've just added a new commit, which seems to work on my end. I've added the ability to pickle the `MDP.Policy` class. So you just have to create a new `MDP.Policy` and use it to copy your `MDP.QGreedyPolicy` (since that cannot be pickled directly).

Then it should just work. Let me know if you have trouble!

**Comment by JFan2016** [comment]
Do I need to rebuild? Currently I do not have g++-7 version. When I tried to install it from ppa: ubuntu-toolchain-r/test, the package could not be found.

**Comment by Svalorzen** [comment]
In theory `g++-6` would work but it seems it has a bug. However, `clang++` seems to work fine. `g++-7` at the moment is only available on Ubuntu 17.04, but as soon as a proper release is done it should definitely be backported to previous versions.

If neither upgrading OS nor using `clang++` is an option for you, you can temporarily use the workaround I specified (storing your `QFunction` by hand and reloading it) until the `g++-7` package is backported.

**Comment by JFan2016** [comment]
About the workaround, the shape of the QFunction is (6084, 4), but when I enter QFunction[6100, 20], I could still get results back. Why?

**Comment by Svalorzen** [comment]
Well if you create a table bigger than what it is it's still going to be able to store the previous one. As long as you don't ask for states/actions which you have not initialized everything should be good =)
