### ISSUE TITLE
Strange behavior in the "tiger_antelope" example

### ISSUE THREAD

**Issue by filippobistaffa** [Svalorzen/AI-Toolbox#24]
I just compiled the latest version of the toolbox (cmake 3.5.1, g++ 7.1.0). Despite of the huge amount of warnings during the compilation, it apparently succeeded, as all the unit tests completed successfully.
I am now trying the "tiger_antelope" example, but the behavior looks a bit strange to me.
- The default 8x8 C++ version looks OK, the tiger is chasing the antelope, eventually catching it in a reasonable amount of steps.
- In the default 5x5 Python version the tiger is not moving at all (I guess the convergence happened when the antelope randomly went onto the tiger).
- If I recompile the C++ version with a grid size of 5x5 (in order to compare it with the Python version on an equal grid), the tiger now only moves up.

Am I expected to see this behavior?

Also, is it normal that the Python version of this example is SO much slower than the C++ version? 
The 8x8 grid example is solved almost instantly with C++, but it takes forever with Python.

**Comment by Svalorzen** [comment]
The warnings unfortunately do not depend from me: the Eigen library seems to be doing things with enums which do not play nicely with `g++-7.0`. They have an open bug report on this, and I hope they will fix it soon. If you actually check you'll see the warnings are always pretty much the same two things, inside the Eigen library.

It is definitely NOT ok that both the Python example nor the C++ version with a 5x5 grid are not working as expected. If the solving process has converged you should expect to see optimal behavior always (if the configuration of the problem was correct), so I'm going to check on this ASAP.

In general is not that Python is slower in solving the problem. It's mostly how the code creates the transition/reward functions ininitally from Python requires lots of loops, which Python dislikes, and so ends up taking a ton of time creating the model and importing it into C++. After that, it's instant.

I'll let you know when things are working properly again, thanks!

**Comment by Svalorzen** [comment]
Hey, I think I found the problem.

I while ago I did some work transitioning from Boost data structures to Eigen, and forgot that Eigen does not automatically zero its matrices. This resulted in a policy with generally random values - it was luck that it worked at all in the normal case!

I've tested this now and it seems to work fine. Let me know if it works or if you have any more problems!

**Comment by filippobistaffa** [comment]
Yup, it seems to work fine now. Thanks!
