### ISSUE TITLE
parse Cassandra file format

### ISSUE THREAD

**Issue by sarming** [Svalorzen/AI-Toolbox#25]
I am wondering if there is already a way to read in files in Tony Cassandra's file format: http://www.pomdp.org/code/pomdp-file-spec.html

**Comment by Svalorzen** [comment]
This was mentioned in #9, unfortunately I never really got to it, but it has always been in the "would love to have" features. There already exists code that does the parsing in other projects (for example https://github.com/AdaCompNUS/sarsop/tree/master/src/Parser), porting it would certainly be nice.

What I wouldn't like would be just copy-pasting the code and wrapping it. For example, the parser code in the project I linked defines its own sparse matrices. Since here we use Eigen, it would be cool to avoid duplicate code. Or, the original code was in C, so there's a bunch of `#ifdef __cplusplus` which would need to be cleaned up. This kind of stuff.

I personally would have loved to do was a new parser using Boost Spirit, but I'm also ok for porting and cleaning up a parser from another project.

Feel free to start a PR for this. If you can manage to make it work (without simply wrapping), I can clean up the code (like the ifdefs and whatnot) and finalize it for the library.

**Comment by Svalorzen** [comment]
Hey, just wanted to let you know that I've implemented a basic parser, and I've pushed it into master. Hope it'll work for you!
