### ISSUE TITLE
Using AI-Toolbox with OMNeT++

### ISSUE THREAD

**Issue by stamourb** [Svalorzen/AI-Toolbox#57]
In order to use AI-Toolbox files in my programs, the only way I've been able to get them to work so far is by adding in my program files within one of the AI-Toolbox folders and adjusting the applicable CMakeLists.txt file before rebuilding the project. I've been looking to use some of the files with an OMNeT++ project, but attempting to use the AI-Toolbox files with that makes it very complicated if I try to just move an OMNeT++ project into the AI-Toolbox folders, because it seems that I would have to change several file paths in potentially hundreds of files.

Would you would happen to have an idea of any simpler way to integrate AI-Toolbox with OMNeT++? Thank you!

**Comment by Svalorzen** [comment]
You can simply create a separate project, with a stand-alone CMakeLists.txt file. Clone AI-Toolbox in a subfolder, say `dependencies`, so that you main folder contains:
```
- CMakeLists.txt
- dependencies/
  - AI-Toolbox/
```
Have the CMakeLists file include the following two lines:
```
add_subdirectory(${PROJECT_SOURCE_DIR}/dependencies/AI-Toolbox)
include_directories(${PROJECT_SOURCE_DIR}/dependencies/AI-Toolbox/include)
```
After that, the new project should automatically compile AI-Toolbox in your local build folder, and you have available the same library symbols to link your executables separately.

**Comment by stamourb** [comment]
Okay, thank you for the help!
